services:
  - type: web
    name: rabotaOVZ-bot
    runtime: python
    buildCommand: |
      pip install pyTelegramBotAPI flask
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: ваш_токен_бота
